# AntsBankNotes
# Thank you for downloading!
# If you have any issues please join my discord and create a ticket.
# Discord: https://discord.link/AntsPlugins
# Please leave a rating on SpigotMC as it really helps!
# Please do not leave error reports in the spigot comments, please use discord instead!


# The item that the BankNote will be.
Money Item: PAPER